<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Lang;

/**
 * App\Setting
 *
 * @property int $id
 * @property string $name
 * @property string $value
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Setting newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Setting newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Setting query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Setting whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Setting whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Setting whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Setting whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Setting whereValue($value)
 * @mixin \Eloquent
 */
class Setting extends Model
{
    protected $fillable = ['name', 'value'];
    
    const PROVIDER_FEE = 12;
    const CUSTOMER_FEE = 3;
    
    const OVERLAYS = ['3' => 3, '4' => 4, '5' => 5, '6' => 6, '7' => 7];
    
    const DEFAULT_SETTINGS = [
        'provider_fee' => self::PROVIDER_FEE,
        'customer_fee' => self::CUSTOMER_FEE,
        'heading' => self::DEFAULT_HEADING,
        'sub_heading' => self::DEFAULT_SUB_HEADING,
    ];
    
    const MESSAGE_TYPES = [
        'all' => 'All Messages',
        'message' => 'Chat Message',
        'refund_request' => 'Refund Request',
        'booking' => 'Subject Booking',
        'request_tutor' => 'Request Tutor'
    ];
    
    const CLASS_SIZE = [
        '1' => '1 Person',
        '10' => '2-10 People',
        '20' => '11-20 People',
        '0' => '21+ People',
    ];
    
    const RATING_OPTIONS = [
        '1' => 1,
        '2' => 2,
        '3' => 3,
        '4' => 4,
        '5' => 5
    ];
    
    const TEACHING_TYPES = [
        'Teacher' => 'Teacher',
        'University Lecturer' => 'University Lecturer',
        'Third Level Student' => 'Third Level Student',
        'Instructor' => 'Instructor',
        'Other' => 'Other',
    ];
    
    const MONTHS = [
        1 => 'January',
        2 => 'February',
        3 => 'March',
        4 => 'April',
        5 => 'May',
        6 => 'June',
        7 => 'July',
        8 => 'August',
        9 => 'September',
        10 => 'October',
        11 => 'November',
        12 => 'December'
    ];
    
    const DEFAULT_HEADING = 'MORE INSPIRING CONNECTIONS, MORE INSPIRING IDEAS FOR MORE INSPIRED KIDS';
    
    const DEFAULT_SUB_HEADING = 'Search for inspiring activities and classes to inspire your kids';
    
    const TWITTER_SHARE_URL = 'https://twitter.com/share';
    const FACEBOOK_SHARE_URL = 'https://www.facebook.com/v4.0/dialog/share?app_id=';
    const MESSENGER_BASE_URL = 'https://www.facebook.com/v4.0/dialog/send?app_id=';
    const MESSENGER_MOBILE_BASE_URL = 'fb-messenger://share?app_id=';
    const MESSENGER_APPEND_URL = 'sharing/reference/send-dialog';
    const WHATSAPP_SHARE_URL = 'https://api.whatsapp.com/send?phone=&text=';
    const WHATSAPP_MOBILE_SHARE_URL = 'https://api.whatsapp.com/send?phone=&text='; //'whatsapp://send?text=';
    
    
    const COUNTRY_CODES = [
        '+44' => 'UK (+44)',
        '+1' => 'USA (+1)',
        '+213' => 'Algeria (+213)',
        '+376' => 'Andorra (+376)',
        '+244' => 'Angola (+244)',
        '+1264' => 'Anguilla (+1264)',
        '+1268' => 'Antigua & Barbuda (+1268)',
        '+54' => 'Argentina (+54)',
        '+374' => 'Armenia (+374)',
        '+297' => 'Aruba (+297)',
        '+61' => 'Australia (+61)',
        '+43' => 'Austria (+43)',
        '+994' => 'Azerbaijan (+994)',
        '+1242' => 'Bahamas (+1242)',
        '+973' => 'Bahrain (+973)',
        '+880' => 'Bangladesh (+880)',
        '+1246' => 'Barbados (+1246)',
        '+375' => 'Belarus (+375)',
        '+32' => 'Belgium (+32)',
        '+501' => 'Belize (+501)',
        '+229' => 'Benin (+229)',
        '+1441' => 'Bermuda (+1441)',
        '+975' => 'Bhutan (+975)',
        '+591' => 'Bolivia (+591)',
        '+387' => 'Bosnia Herzegovina (+387)',
        '+267' => 'Botswana (+267)',
        '+55' => 'Brazil (+55)',
        '+673' => 'Brunei (+673)',
        '+359' => 'Bulgaria (+359)',
        '+226' => 'Burkina Faso (+226)',
        '+257' => 'Burundi (+257)',
        '+855' => 'Cambodia (+855)',
        '+237' => 'Cameroon (+237)',
        '+1' => 'Canada (+1)',
        '+238' => 'Cape Verde Islands (+238)',
        '+1345' => 'Cayman Islands (+1345)',
        '+236' => 'Central African Republic (+236)',
        '+56' => 'Chile (+56)',
        '+86' => 'China (+86)',
        '+57' => 'Colombia (+57)',
        '+269' => 'Comoros (+269)',
        '+242' => 'Congo (+242)',
        '+682' => 'Cook Islands (+682)',
        '+506' => 'Costa Rica (+506)',
        '+385' => 'Croatia (+385)',
        '+53' => 'Cuba (+53)',
        '+90392' => 'Cyprus North (+90392)',
        '+357' => 'Cyprus South (+357)',
        '+42' => 'Czech Republic (+42)',
        '+45' => 'Denmark (+45)',
        '+253' => 'Djibouti (+253)',
        '+1809' => 'Dominica (+1809)',
        '+1809' => 'Dominican Republic (+1809)',
        '+593' => 'Ecuador (+593)',
        '+20' => 'Egypt (+20)',
        '+503' => 'El Salvador (+503)',
        '+240' => 'Equatorial Guinea (+240)',
        '+291' => 'Eritrea (+291)',
        '+372' => 'Estonia (+372)',
        '+251' => 'Ethiopia (+251)',
        '+500' => 'Falkland Islands (+500)',
        '+298' => 'Faroe Islands (+298)',
        '+679' => 'Fiji (+679)',
        '+358' => 'Finland (+358)',
        '+33' => 'France (+33)',
        '+594' => 'French Guiana (+594)',
        '+689' => 'French Polynesia (+689)',
        '+241' => 'Gabon (+241)',
        '+220' => 'Gambia (+220)',
        '+7880' => 'Georgia (+7880)',
        '+49' => 'Germany (+49)',
        '+233' => 'Ghana (+233)',
        '+350' => 'Gibraltar (+350)',
        '+30' => 'Greece (+30)',
        '+299' => 'Greenland (+299)',
        '+1473' => 'Grenada (+1473)',
        '+590' => 'Guadeloupe (+590)',
        '+671' => 'Guam (+671)',
        '+502' => 'Guatemala (+502)',
        '+224' => 'Guinea (+224)',
        '+245' => 'Guinea - Bissau (+245)',
        '+592' => 'Guyana (+592)',
        '+509' => 'Haiti (+509)',
        '+504' => 'Honduras (+504)',
        '+852' => 'Hong Kong (+852)',
        '+36' => 'Hungary (+36)',
        '+354' => 'Iceland (+354)',
        '+91' => 'India (+91)',
        '+62' => 'Indonesia (+62)',
        '+98' => 'Iran (+98)',
        '+964' => 'Iraq (+964)',
        '+353' => 'Ireland (+353)',
        '+972' => 'Israel (+972)',
        '+39' => 'Italy (+39)',
        '+1876' => 'Jamaica (+1876)',
        '+81' => 'Japan (+81)',
        '+962' => 'Jordan (+962)',
        '+7' => 'Kazakhstan (+7)',
        '+254' => 'Kenya (+254)',
        '+686' => 'Kiribati (+686)',
        '+850' => 'Korea North (+850)',
        '+82' => 'Korea South (+82)',
        '+965' => 'Kuwait (+965)',
        '+996' => 'Kyrgyzstan (+996)',
        '+856' => 'Laos (+856)',
        '+371' => 'Latvia (+371)',
        '+961' => 'Lebanon (+961)',
        '+266' => 'Lesotho (+266)',
        '+231' => 'Liberia (+231)',
        '+218' => 'Libya (+218)',
        '+417' => 'Liechtenstein (+417)',
        '+370' => 'Lithuania (+370)',
        '+352' => 'Luxembourg (+352)',
        '+853' => 'Macao (+853)',
        '+389' => 'Macedonia (+389)',
        '+261' => 'Madagascar (+261)',
        '+265' => 'Malawi (+265)',
        '+60' => 'Malaysia (+60)',
        '+960' => 'Maldives (+960)',
        '+223' => 'Mali (+223)',
        '+356' => 'Malta (+356)',
        '+692' => 'Marshall Islands (+692)',
        '+596' => 'Martinique (+596)',
        '+222' => 'Mauritania (+222)',
        '+269' => 'Mayotte (+269)',
        '+52' => 'Mexico (+52)',
        '+691' => 'Micronesia (+691)',
        '+373' => 'Moldova (+373)',
        '+377' => 'Monaco (+377)',
        '+976' => 'Mongolia (+976)',
        '+1664' => 'Montserrat (+1664)',
        '+212' => 'Morocco (+212)',
        '+258' => 'Mozambique (+258)',
        '+95' => 'Myanmar (+95)',
        '+264' => 'Namibia (+264)',
        '+674' => 'Nauru (+674)',
        '+977' => 'Nepal (+977)',
        '+31' => 'Netherlands (+31)',
        '+687' => 'New Caledonia (+687)',
        '+64' => 'New Zealand (+64)',
        '+505' => 'Nicaragua (+505)',
        '+227' => 'Niger (+227)',
        '+234' => 'Nigeria (+234)',
        '+683' => 'Niue (+683)',
        '+672' => 'Norfolk Islands (+672)',
        '+670' => 'Northern Marianas (+670)',
        '+47' => 'Norway (+47)',
        '+968' => 'Oman (+968)',
        '+680' => 'Palau (+680)',
        '+507' => 'Panama (+507)',
        '+675' => 'Papua New Guinea (+675)',
        '+595' => 'Paraguay (+595)',
        '+51' => 'Peru (+51)',
        '+63' => 'Philippines (+63)',
        '+48' => 'Poland (+48)',
        '+351' => 'Portugal (+351)',
        '+1787' => 'Puerto Rico (+1787)',
        '+974' => 'Qatar (+974)',
        '+262' => 'Reunion (+262)',
        '+40' => 'Romania (+40)',
        '+7' => 'Russia (+7)',
        '+250' => 'Rwanda (+250)',
        '+378' => 'San Marino (+378)',
        '+239' => 'Sao Tome & Principe (+239)',
        '+966' => 'Saudi Arabia (+966)',
        '+221' => 'Senegal (+221)',
        '+381' => 'Serbia (+381)',
        '+248' => 'Seychelles (+248)',
        '+232' => 'Sierra Leone (+232)',
        '+65' => 'Singapore (+65)',
        '+21' => 'Slovak Republic (+421)',
        '+386' => 'Slovenia (+386)',
        '+677' => 'Solomon Islands (+677)',
        '+252' => 'Somalia (+252)',
        '+27' => 'South Africa (+27)',
        '+34' => 'Spain (+34)',
        '+94' => 'Sri Lanka (+94)',
        '+290' => 'St. Helena (+290)',
        '+1869' => 'St. Kitts (+1869)',
        '+1758' => 'St. Lucia (+1758)',
        '+249' => 'Sudan (+249)',
        '+597' => 'Suriname (+597)',
        '+268' => 'Swaziland (+268)',
        '+46' => 'Sweden (+46)',
        '+41' => 'Switzerland (+41)',
        '+963' => 'Syria (+963)',
        '+886' => 'Taiwan (+886)',
        '+7' => 'Tajikstan (+7)',
        '+66' => 'Thailand (+66)',
        '+228' => 'Togo (+228)',
        '+676' => 'Tonga (+676)',
        '+1868' => 'Trinidad & Tobago (+1868)',
        '+216' => 'Tunisia (+216)',
        '+90' => 'Turkey (+90)',
        '+7' => 'Turkmenistan (+7)',
        '+993' => 'Turkmenistan (+993)',
        '+1649' => 'Turks & Caicos Islands (+1649)',
        '+688' => 'Tuvalu (+688)',
        '+256' => 'Uganda (+256)',
        '+380' => 'Ukraine (+380)',
        '+971' => 'United Arab Emirates (+971)',
        '+598' => 'Uruguay (+598)',
        '+7' => 'Uzbekistan (+7)',
        '+678' => 'Vanuatu (+678)',
        '+379' => 'Vatican City (+379)',
        '+58' => 'Venezuela (+58)',
        '+84' => 'Vietnam (+84)',
        '+84' => 'Virgin Islands - British (+1284)',
        '+84' => 'Virgin Islands - US (+1340)',
        '+681' => 'Wallis & Futuna (+681)',
        '+969' => 'Yemen (North)(+969)',
        '+967' => 'Yemen (South)(+967)',
        '+260' => 'Zambia (+260)',
        '+263' => 'Zimbabwe (+263)',
    ];
    
    const STRIPE_MCC = [
        '7623' => 'A/C, Refrigeration Repair',
        '8931' => 'Accounting/Bookkeeping Services',
        '7311' => 'Advertising Services',
        '0763' => 'Agricultural Cooperative',
        '4511' => 'Airlines, Air Carriers',
        '4582' => 'Airports, Flying Fields',
        '4119' => 'Ambulance Services',
        '7996' => 'Amusement Parks/Carnivals',
        '5937' => 'Antique Reproductions',
        '5932' => 'Antique Shops',
        '7998' => 'Aquariums',
        '8911' => 'Architectural/Surveying Services',
        '5971' => 'Art Dealers and Galleries',
        '5970' => 'Artists Supply and Craft Shops',
        '7531' => 'Auto Body Repair Shops',
        '7535' => 'Auto Paint Shops',
        '7538' => 'Auto Service Shops',
        '5531' => 'Auto and Home Supply Stores',
        '6011' => 'Automated Cash Disburse',
        '5542' => 'Automated Fuel Dispensers',
        '8675' => 'Automobile Associations',
        '5533' => 'Automotive Parts and Accessories Stores',
        '5532' => 'Automotive Tire Stores',
        '9223' => 'Bail and Bond Payments (payment to the surety for the bond, not the actual bond paid to the government agency)',
        '5462' => 'Bakeries',
        '7929' => 'Bands, Orchestras',
        '7230' => 'Barber and Beauty Shops',
        '7995' => 'Betting/Casino Gambling',
        '5940' => 'Bicycle Shops',
        '7932' => 'Billiard/Pool Establishments',
        '5551' => 'Boat Dealers',
        '4457' => 'Boat Rentals and Leases',
        '5942' => 'Book Stores',
        '5192' => 'Books, Periodicals, and Newspapers',
        '7933' => 'Bowling Alleys',
        '4131' => 'Bus Lines',
        '8244' => 'Business/Secretarial Schools',
        '7278' => 'Buying/Shopping Services',
        '4899' => 'Cable, Satellite, and Other Pay Television and Radio',
        '5946' => 'Camera and Photographic Supply Stores',
        '5441' => 'Candy, Nut, and Confectionery Stores',
        '7512' => 'Car Rental Agencies',
        '7542' => 'Car Washes',
        '5511' => 'Car and Truck Dealers (New & Used) Sales, Service, Repairs Parts and Leasing',
        '5521' => 'Car and Truck Dealers (Used Only) Sales, Service, Repairs Parts and Leasing',
        '1750' => 'Carpentry Services',
        '7217' => 'Carpet/Upholstery Cleaning',
        '5811' => 'Caterers',
        '8398' => 'Charitable and Social Service Organizations - Fundraising',
        '5169' => 'Chemicals and Allied Products (Not Elsewhere Classified)',
        '8351' => 'Child Care Services',
        '5641' => 'Childrens and Infants Wear Stores',
        '8049' => 'Chiropodists, Podiatrists',
        '8041' => 'Chiropractors',
        '5993' => 'Cigar Stores and Stands',
        '8641' => 'Civic, Social, Fraternal Associations',
        '7349' => 'Cleaning and Maintenance',
        '7296' => 'Clothing Rental',
        '8220' => 'Colleges, Universities',
        '5046' => 'Commercial Equipment (Not Elsewhere Classified)',
        '5139' => 'Commercial Footwear',
        '7333' => 'Commercial Photography, Art and Graphics',
        '4111' => 'Commuter Transport, Ferries',
        '4816' => 'Computer Network Services',
        '7372' => 'Computer Programming',
        '7379' => 'Computer Repair',
        '5734' => 'Computer Software Stores',
        '5045' => 'Computers, Peripherals, and Software',
        '1771' => 'Concrete Work Services',
        '5039' => 'Construction Materials (Not Elsewhere Classified)',
        '7392' => 'Consulting, Public Relations',
        '8241' => 'Correspondence Schools',
        '5977' => 'Cosmetic Stores',
        '7277' => 'Counseling Services',
        '7997' => 'Country Clubs',
        '4215' => 'Courier Services',
        '9211' => 'Court Costs, Including Alimony and Child Support - Courts of Law',
        '7321' => 'Credit Reporting Agencies',
        '4411' => 'Cruise Lines',
        '5451' => 'Dairy Products Stores',
        '7911' => 'Dance Hall, Studios, Schools',
        '7273' => 'Dating/Escort Services',
        '8021' => 'Dentists, Orthodontists',
        '5311' => 'Department Stores',
        '7393' => 'Detective Agencies',
        '5815' => 'Digital Goods Media – Books, Movies, Music',
        '5817' => 'Digital Goods – Applications (Excludes Games)',
        '5816' => 'Digital Goods – Games',
        '5818' => 'Digital Goods – Large Digital Goods Merchant',
        '5964' => 'Direct Marketing - Catalog Merchant',
        '5965' => 'Direct Marketing - Combination Catalog and Retail Merchant',
        '5967' => 'Direct Marketing - Inbound Telemarketing',
        '5960' => 'Direct Marketing - Insurance Services',
        '5969' => 'Direct Marketing - Other',
        '5966' => 'Direct Marketing - Outbound Telemarketing',
        '5968' => 'Direct Marketing - Subscription',
        '5962' => 'Direct Marketing - Travel',
        '5310' => 'Discount Stores',
        '8011' => 'Doctors',
        '5963' => 'Door-To-Door Sales',
        '5714' => 'Drapery, Window Covering, and Upholstery Stores',
        '5813' => 'Drinking Places',
        '5912' => 'Drug Stores and Pharmacies',
        '5122' => 'Drugs, Drug Proprietaries, and Druggist Sundries',
        '7216' => 'Dry Cleaners',
        '5099' => 'Durable Goods (Not Elsewhere Classified)',
        '5309' => 'Duty Free Stores',
        '5812' => 'Eating Places, Restaurants',
        '8299' => 'Educational Services',
        '5997' => 'Electric Razor Stores',
        '5065' => 'Electrical Parts and Equipment',
        '1731' => 'Electrical Services',
        '7622' => 'Electronics Repair Shops',
        '5732' => 'Electronics Stores',
        '8211' => 'Elementary, Secondary Schools',
        '7361' => 'Employment/Temp Agencies',
        '7394' => 'Equipment Rental',
        '7342' => 'Exterminating Services',
        '5651' => 'Family Clothing Stores',
        '5814' => 'Fast Food Restaurants',
        '6012' => 'Financial Institutions',
        '9222' => 'Fines - Government Administrative Entities',
        '5718' => 'Fireplace, Fireplace Screens, and Accessories Stores',
        '5713' => 'Floor Covering Stores',
        '5992' => 'Florists',
        '5193' => 'Florists Supplies, Nursery Stock, and Flowers',
        '5422' => 'Freezer and Locker Meat Provisioners',
        '5983' => 'Fuel Dealers (Non Automotive)',
        '7261' => 'Funeral Services, Crematories',
        '7641' => 'Furniture Repair, Refinishing',
        '5712' => 'Furniture, Home Furnishings, and Equipment Stores, Except Appliances',
        '5681' => 'Furriers and Fur Shops',
        '1520' => 'General Services',
        '5947' => 'Gift, Card, Novelty, and Souvenir Shops',
        '5231' => 'Glass, Paint, and Wallpaper Stores',
        '5950' => 'Glassware, Crystal Stores',
        '7992' => 'Golf Courses - Public',
        '9399' => 'Government Services (Not Elsewhere Classified)',
        '5411' => 'Grocery Stores, Supermarkets',
        '5251' => 'Hardware Stores',
        '5072' => 'Hardware, Equipment, and Supplies',
        '7298' => 'Health and Beauty Spas',
        '5975' => 'Hearing Aids Sales and Supplies',
        '1711' => 'Heating, Plumbing, A/C',
        '5945' => 'Hobby, Toy, and Game Shops',
        '5200' => 'Home Supply Warehouse Stores',
        '8062' => 'Hospitals',
        '7011' => 'Hotels, Motels, and Resorts',
        '5722' => 'Household Appliance Stores',
        '5085' => 'Industrial Supplies (Not Elsewhere Classified)',
        '7375' => 'Information Retrieval Services',
        '6399' => 'Insurance - Default',
        '6300' => 'Insurance Underwriting, Premiums',
        '9950' => 'Intra-Company Purchases',
        '5944' => 'Jewelry Stores, Watches, Clocks, and Silverware Stores',
        '0780' => 'Landscaping Services',
        '7211' => 'Laundries',
        '7210' => 'Laundry, Cleaning Services',
        '8111' => 'Legal Services, Attorneys',
        '5948' => 'Luggage and Leather Goods Stores',
        '5211' => 'Lumber, Building Materials Stores',
        '6010' => 'Manual Cash Disburse',
        '4468' => 'Marinas, Service and Supplies',
        '1740' => 'Masonry, Stonework, and Plaster',
        '7297' => 'Massage Parlors',
        '8099' => 'Medical Services',
        '8071' => 'Medical and Dental Labs',
        '5047' => 'Medical, Dental, Ophthalmic, and Hospital Equipment and Supplies',
        '8699' => 'Membership Organizations',
        '5611' => 'Mens and Boys Clothing and Accessories Stores',
        '5691' => 'Mens, Womens Clothing Stores',
        '5051' => 'Metal Service Centers',
        '5699' => 'Miscellaneous Apparel and Accessory Shops',
        '5599' => 'Miscellaneous Auto Dealers',
        '7399' => 'Miscellaneous Business Services',
        '5499' => 'Miscellaneous Food Stores - Convenience Stores and Specialty Markets',
        '5399' => 'Miscellaneous General Merchandise',
        '7299' => 'Miscellaneous General Services',
        '5719' => 'Miscellaneous Home Furnishing Specialty Stores',
        '2741' => 'Miscellaneous Publishing and Printing',
        '7999' => 'Miscellaneous Recreation Services',
        '7699' => 'Miscellaneous Repair Shops',
        '5999' => 'Miscellaneous Specialty Retail',
        '5271' => 'Mobile Home Dealers',
        '7832' => 'Motion Picture Theaters',
        '4214' => 'Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services',
        '5592' => 'Motor Homes Dealers',
        '5013' => 'Motor Vehicle Supplies and New Parts',
        '5571' => 'Motorcycle Shops and Dealers',
        '5561' => 'Motorcycle Shops, Dealers',
        '5733' => 'Music Stores-Musical Instruments, Pianos, and Sheet Music',
        '5994' => 'News Dealers and Newsstands',
        '6051' => 'Non-FI, Money Orders',
        '6540' => 'Non-FI, Stored Value Card Purchase/Load',
        '5199' => 'Nondurable Goods (Not Elsewhere Classified)',
        '5261' => 'Nurseries, Lawn and Garden Supply Stores',
        '8050' => 'Nursing/Personal Care',
        '5021' => 'Office and Commercial Furniture',
        '8043' => 'Opticians, Eyeglasses',
        '8042' => 'Optometrists, Ophthalmologist',
        '5976' => 'Orthopedic Goods - Prosthetic Devices',
        '8031' => 'Osteopaths',
        '5921' => 'Package Stores-Beer, Wine, and Liquor',
        '5198' => 'Paints, Varnishes, and Supplies',
        '7523' => 'Parking Lots, Garages',
        '4112' => 'Passenger Railways',
        '5933' => 'Pawn Shops',
        '5995' => 'Pet Shops, Pet Food, and Supplies',
        '5172' => 'Petroleum and Petroleum Products',
        '7395' => 'Photo Developing',
        '7221' => 'Photographic Studios',
        '5044' => 'Photographic, Photocopy, Microfilm Equipment, and Supplies',
        '7829' => 'Picture/Video Production',
        '5131' => 'Piece Goods, Notions, and Other Dry Goods',
        '5074' => 'Plumbing, Heating Equipment, and Supplies',
        '8651' => 'Political Organizations',
        '9402' => 'Postal Services - Government Only',
        '5094' => 'Precious Stones and Metals, Watches and Jewelry',
        '8999' => 'Professional Services',
        '4225' => 'Public Warehousing and Storage - Farm Products, Refrigerated Goods, Household Goods, and Storage',
        '7338' => 'Quick Copy, Repro, and Blueprint',
        '4011' => 'Railroads',
        '6513' => 'Real Estate Agents and Managers - Rentals',
        '5735' => 'Record Stores',
        '7519' => 'Recreational Vehicle Rentals',
        '5973' => 'Religious Goods Stores',
        '8661' => 'Religious Organizations',
        '1761' => 'Roofing/Siding, Sheet Metal',
        '7339' => 'Secretarial Support Services',
        '6211' => 'Security Brokers/Dealers',
        '5541' => 'Service Stations',
        '5949' => 'Sewing, Needlework, Fabric, and Piece Goods Stores',
        '7251' => 'Shoe Repair/Hat Cleaning',
        '5661' => 'Shoe Stores',
        '7629' => 'Small Appliance Repair',
        '5598' => 'Snowmobile Dealers',
        '1799' => 'Special Trade Services',
        '2842' => 'Specialty Cleaning',
        '5941' => 'Sporting Goods Stores',
        '7032' => 'Sporting/Recreation Camps',
        '7941' => 'Sports Clubs/Fields',
        '5655' => 'Sports and Riding Apparel Stores',
        '5972' => 'Stamp and Coin Stores',
        '5111' => 'Stationary, Office Supplies, Printing and Writing Paper',
        '5943' => 'Stationery Stores, Office, and School Supply Stores',
        '5996' => 'Swimming Pools Sales',
        '4723' => 'TUI Travel - Germany',
        '5697' => 'Tailors, Alterations',
        '9311' => 'Tax Payments - Government Agencies',
        '7276' => 'Tax Preparation Services',
        '4121' => 'Taxicabs/Limousines',
        '4812' => 'Telecommunication Equipment and Telephone Sales',
        '4814' => 'Telecommunication Services',
        '4821' => 'Telegraph Services',
        '5998' => 'Tent and Awning Shops',
        '8734' => 'Testing Laboratories',
        '7922' => 'Theatrical Ticket Agencies',
        '7012' => 'Timeshares',
        '7534' => 'Tire Retreading and Repair',
        '4784' => 'Tolls/Bridge Fees',
        '7991' => 'Tourist Attractions and Exhibits',
        '7549' => 'Towing Services',
        '7033' => 'Trailer Parks, Campgrounds',
        '4789' => 'Transportation Services (Not Elsewhere Classified)',
        '4722' => 'Travel Agencies, Tour Operators',
        '7511' => 'Truck StopIteration',
        '7513' => 'Truck/Utility Trailer Rentals',
        '2791' => 'Typesetting, Plate Making, and Related Services',
        '5978' => 'Typewriter Stores',
        '9405' => 'U.S. Federal Government Agencies or Departments',
        '5137' => 'Uniforms, Commercial Clothing',
        '5931' => 'Used Merchandise and Secondhand Stores',
        '4900' => 'Utilities',
        '5331' => 'Variety Stores',
        '0742' => 'Veterinary Services',
        '7993' => 'Video Amusement Game Supplies',
        '7994' => 'Video Game Arcades',
        '7841' => 'Video Tape Rental Stores',
        '8249' => 'Vocational/Trade Schools',
        '7631' => 'Watch/Jewelry Repair',
        '7692' => 'Welding Repair',
        '5300' => 'Wholesale Clubs',
        '5698' => 'Wig and Toupee Stores',
        '4829' => 'Wires, Money Orders',
        '5631' => 'Womens Accessory and Specialty Shops',
        '5621' => 'Womens Ready-To-Wear Stores',
        '5935' => 'Wrecking and Salvage Yards'
    ];
    
    const STRIPE_REQUIMENT_KEYS = [
        'business_profile.mcc' => 'Industry/Merchant Category Code',
        'verification.document' => 'ID Documents',
        'verification.additional_document' => 'Additional Documents',
        'company.phone' => 'Company Phone Number'
    ];
    
    public static function get($name)
    {
        try {
            return self::where('name', $name)->first()->value;
            
        } catch (\Exception $e) {
            if (array_key_exists($name, self::DEFAULT_SETTINGS)) {
                return self::DEFAULT_SETTINGS[$name];
            }
            
            return '';
        }
    }
}

